all:
	make -C src

# Phony targets
.PHONY: all clean distclean install

# Standard clean
clean:
	make -C src clean

distclean:
	make -C src distclean
	rm bin/* bin/.keep

install:
	make -C src install
